- hosts: all
  vars:
  # This section is only needed if you want to send a discord notification about running this playbook
    notify_discord_username: Ansible
    notify_discord_webhook_id: ''
    notify_discord_webhook_token: ''
    notify_discord_webhook_id_regex: '^0|[1-9][0-9]*$'
    notify_discord_webhook_token_regex: '^[a-zA-Z0-9_-]+$'
    notify_discord_webhook_content: |-
      **Message from localhost by *Ansible* **
      Updating apt packages/removing old ones!
    notify_discord_send_from_host: localhost

  tasks:
    - name: Update packages with apt
      become: true
      become_user: root
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes

    - name: Upgrade packages with apt
      become: true
      become_user: root
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: yes
      register: apt_update

    - name: Remove dependencies that are no longer required.
      become: true
      become_user: root
      ansible.builtin.apt:
        autoremove: yes
        force_apt_get: yes

    - name: Send Discord message
      community.general.discord:
        username: "{{ notify_discord_username }}"
        webhook_id: "{{ notify_discord_webhook_id }}"
        webhook_token: "{{ notify_discord_webhook_token }}"
        content: "{{ notify_discord_webhook_content }}"
      delegate_to: "{{ notify_discord_send_from_host }}"
      when:
        - notify_discord_webhook_id is match(notify_discord_webhook_id_regex)
        - notify_discord_webhook_token is match(notify_discord_webhook_token_regex)
        - notify_discord_webhook_content | length > 0
        - notify_discord_send_from_host is in (['localhost'] + groups['all'])
        - apt_update is changed